name: "HunyuanDiT-overfit-mini"

training:
  steps: 800               # mini数据集上更好的选择800步即可满足需求
  base_lr: 5e-5            # 提高模型的相关过拟合性，稍降学习率
  val_check_interval: 9999 # 不验证
  limit_val_batches: 0
  every_n_train_steps: 200 # 每 200 步存一次 ckpt
  monitor: null            # 关闭 monitor

dataset:
  target: hy3dshape.data.dit_asl.AlignedShapeLatentModule
  params:
    batch_size: 1          # 单卡单样本
    num_workers: 4
    train_data_list: tools/tiny_trainset/preprocessed  # 指向 1 个样本
    val_data_list: tools/tiny_trainset/preprocessed
    image_size: 518
    mean: [0.5,0.5,0.5]
    std:  [0.5,0.5,0.5]
    pc_size: 8192          # 降采样，减少显存
    return_normal: true
    padding: true
    augmentation:          # 轻量增强
      rotation: 15
      scale: [0.9,1.1]

model:
  target: hy3dshape.models.diffusion.flow_matching_sit.Diffuser
  params:
    first_stage_config:
      target: hy3dshape.models.autoencoders.ShapeVAE
      from_pretrained: tencent/Hunyuan3D-2.1
    denoiser_cfg:
      target: hy3dshape.models.denoisers.hunyuandit.HunYuanDiTPlain
      params:
        input_size: 1024     # 4096→1024，显存减半
        in_channels: 64
        hidden_size: 1024    # 2048→1024
        depth: 8             # 16→8
        context_dim: 1024
        num_heads: 8
        dropout: 0.1         # 新增
    optimizer_cfg:
      optimizer:
        target: torch.optim.AdamW
        params:
          weight_decay: 1e-2